### ISSUE TITLE
self.builder = trt.Builder(self.trt_logger) TypeError: pybind11::init(): factory function returned nullptr

### ISSUE THREAD

**Issue by imenselmi** [swapkh91/detectron2-to-tensorrt#2]
i have : 
$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

 $ nvidia-smi

Thu Jun 22 13:58:57 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   45C    P0     5W /  N/A |     10MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1264      G   /usr/lib/xorg/Xorg                  4MiB |
|    0   N/A  N/A      2017      G   /usr/lib/xorg/Xorg                  4MiB |
+-----------------------------------------------------------------------------+
and i have in bashrc: 
export CUDA_HOME="/usr/local/cuda-11.8"
export DYLD_LIBRARY_PATH=$CUDA_HOME/lib64:$DYLD_LIBRARY_PATH
export PATH=$CUDA_HOME/bin:$PATH
export C_INCLUDE_PATH=$CUDA_HOME/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$CUDA_HOME/include:$CPLUS_INCLUDE_PATH
export LD_LIBRARY_PATH=$CUDA_HOME/lib64:$LD_LIBRARY_PATH
export LD_RUN_PATH=$CUDA_HOME/lib64:$LD_RUN_PATH
export TRT_LIBPATH="/home/mj/Downloads/TensorRT-8.6.1.6"
**************
but wheni ran this command i faced this error:
$G5-5500:~/tao-experiments/detectron$     python3 /home/mj/tao-experiments/detectron/TensorRT/samples/python/detectron2/build_engine.py     --onnx /home/mj/tao-experiments/detectron/model.onnx     --engine engine.trt     --precision fp16
[06/22/2023-13:59:58] [TRT] [W] Unable to determine GPU memory usage
[06/22/2023-13:59:58] [TRT] [W] Unable to determine GPU memory usage
[06/22/2023-13:59:58] [TRT] [I] [MemUsageChange] Init CUDA: CPU +0, GPU +0, now: CPU 93, GPU 0 (MiB)
[06/22/2023-13:59:58] [TRT] [W] CUDA initialization failure with error: 35. Please check your CUDA installation:  http://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html
Traceback (most recent call last):
  File "/home/mj/tao-experiments/detectron/TensorRT/samples/python/detectron2/build_engine.py", line 249, in <module>
    main(args)
  File "/home/mj/tao-experiments/detectron/TensorRT/samples/python/detectron2/build_engine.py", line 217, in main
    builder = EngineBuilder(args.verbose, args.workspace)
  File "/home/mj/tao-experiments/detectron/TensorRT/samples/python/detectron2/build_engine.py", line 131, in __init__
    self.builder = trt.Builder(self.trt_logger)
TypeError: pybind11::init(): factory function returned nullptr

can you share with me the cuda version , driver and tensorrt version for solve this problem

**Comment by swapkh91** [comment]
the cuda version is 11.7
but I'm installing these separately. I've used nvidia's official pytorch image 22.08 which already has tensorrt 
[conainer contents link](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_22-08.html)
you can follow the steps in my blog post to set it up, link in readme
